services:
  backend:
    container_name: interviewer-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5035:5035"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5035
      ConnectionStrings__MongoDb: "mongodb://mongo-db:27017"
    depends_on:
      - mongo
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
