name: CD - Docker Build & Push

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # DockerHub Login
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # GHCR Login (using GITHUB_TOKEN with packages scope)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: Saubhik998
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push to both registries in a single step
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./AudioInterviewer.API
          file: ./AudioInterviewer.API/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/audio-interviewer-api:latest
            ghcr.io/saubhik998/audio-interviewer-api:latest
