name: CI dotnet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --quiet --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.406'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --no-restore

      - name: Set ASP.NET Core environment variables
        run: |
          echo "DOTNET_ENVIRONMENT=Development" >> $GITHUB_ENV
          echo "ASPNETCORE_CONTENTROOT=$(pwd)/AudioInterviewer.API" >> $GITHUB_ENV

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4 
        with:
          name: test-results
          path: '**/TestResults/*.trx'
